//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// xscgen C:\Users\Elykomov\Documents\smev-service-adapter.xsd
namespace SMEV.Adapter.XsdTypes
{
    
    
    /// <summary>
    /// <para>Запрос невозможно отправить Адаптером СМЭВ по причине программного сбоя либо
    ///                отсутствия необходимой конфигурационной информации.
    ///                Действия клиента: должен предпринимать повторные попытки отправить запрос, без ограничения количества
    ///                попыток.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Запрос невозможно отправить Адаптером СМЭВ по причине программного сбоя либо отсу" +
        "тствия необходимой конфигурационной информации. Действия клиента: должен предпри" +
        "нимать повторные попытки отправить запрос, без ограничения количества попыток.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SystemFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SystemFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    public partial class SystemFault : Fault
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Fault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidationFault))]
    public partial class Fault
    {
        
        /// <summary>
        /// <para>Код ошибки, генерируемый Адаптером СМЭВ либо возвращаемый СМЭВ 3</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код ошибки, генерируемый Адаптером СМЭВ либо возвращаемый СМЭВ 3")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public string Code { get; set; }
        
        /// <summary>
        /// <para>Описание ошибки, генерируемое Адаптером СМЭВ либо возвращаемое СМЭВ 3</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание ошибки, генерируемое Адаптером СМЭВ либо возвращаемое СМЭВ 3")]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
    }
    
    /// <summary>
    /// <para>Ошибка обработки запроса Адаптером СМЭВ по причине отсутствия в запросе данных необходимых для его
    ///                обработки либо
    ///                наличия в запросе неконсистентных данных.
    ///                Действия клиента: должен устранить причину ошибки обработки запроса и предпринять повторную попытку
    ///                отправить запрос.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Ошибка обработки запроса Адаптером СМЭВ по причине отсутствия в запросе данных необходимых для его обработки либо наличия в запросе неконсистентных данных. Действия клиента: должен устранить причину ошибки обработки запроса и предпринять повторную попытку отправить запрос.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValidationFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ValidationFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    public partial class ValidationFault : Fault
    {
    }
    
    /// <summary>
    /// <para>Адаптер СМЭВ не получил синхронный ответ на отправленный запрос в течение заданного времени.
    ///                Действия клиента: должен предпринимать повторные попытки отправить запрос, без ограничения количества
    ///                попыток.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Адаптер СМЭВ не получил синхронный ответ на отправленный запрос в течение заданно" +
        "го времени. Действия клиента: должен предпринимать повторные попытки отправить з" +
        "апрос, без ограничения количества попыток.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SyncFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SyncFault", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types/faults")]
    public partial class SyncFault : Fault
    {
    }
}
