//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// xscgen C:\Users\Elykomov\Documents\smev-service-adapter.xsd
namespace SMEV.Adapter.XsdTypes
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RejectCode", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum RejectCode
    {

        /// <summary>
        /// <para>Отсутствуют права на получение информации (например, в случае, если поставщик проверяет ЭП-СП).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Отсутствуют права на получение информации (например, в случае, если поставщик про" +
            "веряет ЭП-СП).")]
        [System.Xml.Serialization.XmlEnumAttribute("ACCESS_DENIED")]
        AccessDenied,

        /// <summary>
        /// <para>Сведения отсутствуют.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения отсутствуют.")]
        [System.Xml.Serialization.XmlEnumAttribute("NO_DATA")]
        NoData,

        /// <summary>
        /// <para>Невозможно определить объект запроса информации.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Невозможно определить объект запроса информации.")]
        [System.Xml.Serialization.XmlEnumAttribute("UNKNOWN_REQUEST_DESCRIPTION")]
        UnknownRequestDescription,

        /// <summary>
        /// <para>Ошибка.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ошибка.")]
        [System.Xml.Serialization.XmlEnumAttribute("FAILURE")]
        Failure,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QueryTypeCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryTypeCriteria
    {

        /// <summary>
        /// <para>Получение одного сообщения из адаптера по его типу.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получение одного сообщения из адаптера по его типу.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("messageTypeCriteria")]
        public TypeCriteria MessageTypeCriteria { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TypeCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum TypeCriteria
    {

        /// <summary>
        /// <para>Получить ответ на запрос.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получить ответ на запрос.")]
        [System.Xml.Serialization.XmlEnumAttribute("RESPONSE")]
        Response,

        /// <summary>
        /// <para>Получить запрос.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получить запрос.")]
        [System.Xml.Serialization.XmlEnumAttribute("REQUEST")]
        Request,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FindTypeCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindTypeCriteria
    {

        /// <summary>
        /// <para>Получение сообщений из адаптера за заданный период времени.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получение сообщений из адаптера за заданный период времени.")]
        [System.Xml.Serialization.XmlElementAttribute("messagePeriodCriteria")]
        public MessagePeriodCriteria MessagePeriodCriteria { get; set; }

        /// <summary>
        /// <para>Получение сообщений из адаптера по его клиентскому идентификатору.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получение сообщений из адаптера по его клиентскому идентификатору.")]
        [System.Xml.Serialization.XmlElementAttribute("messageClientIdCriteria")]
        public MessageClientIdCriteria MessageClientIdCriteria { get; set; }

        /// <summary>
        /// <para>Количество вовращаемых сообщений</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Количество вовращаемых сообщений")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("MessageCountToReturn")]
        public int MessageCountToReturn { get; set; }

        /// <summary>
        /// <para>Сдвиг по списку сообщений</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сдвиг по списку сообщений")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("MessageOffset")]
        public int MessageOffset { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("messagePeriodCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessagePeriodCriteria
    {

        /// <summary>
        /// <para>От. Если не указан //to, то возвращаются все сообщения начиная с //from.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("От. Если не указан //to, то возвращаются все сообщения начиная с //from.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("from", DataType = "dateTime")]
        public System.DateTime From { get; set; }

        /// <summary>
        /// <para>До.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("До.")]
        [System.Xml.Serialization.XmlElementAttribute("to", DataType = "dateTime")]
        public System.DateTime To { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the To property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MessageClientIdCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageClientIdCriteria
    {

        /// <summary>
        /// <para>Клиентский идентификатор сообщения.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Клиентский идентификатор сообщения.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// <para>Вариант получения сообщения из адаптера по клиентскому идентификатору сообщения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Вариант получения сообщения из адаптера по клиентскому идентификатору сообщения.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("clientIdCriteria")]
        public ClientIdCriteria ClientIdCriteria { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClientIdCriteria", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum ClientIdCriteria
    {

        /// <summary>
        /// <para>Получить запрос по клиентскому идентификатору запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получить запрос по клиентскому идентификатору запроса.")]
        [System.Xml.Serialization.XmlEnumAttribute("GET_REQUEST_BY_REQUEST_CLIENTID")]
        GetRequestByRequestClientid,

        /// <summary>
        /// <para>Получить все ответы на запрос по клиентскому идентификатору запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получить все ответы на запрос по клиентскому идентификатору запроса.")]
        [System.Xml.Serialization.XmlEnumAttribute("GET_RESPONSE_BY_REQUEST_CLIENTID")]
        GetResponseByRequestClientid,

        /// <summary>
        /// <para>Получить ответ на запрос по клиентскому идентификатору ответа на запрос.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Получить ответ на запрос по клиентскому идентификатору ответа на запрос.")]
        [System.Xml.Serialization.XmlEnumAttribute("GET_RESPONSE_BY_RESPONSE_CLIENTID")]
        GetResponseByResponseClientid,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequestMetadataType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RequestMetadata", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class RequestMetadataType : Metadata
    {

        /// <summary>
        /// <para>Необходим для привязывания запроса к последовательности запросов либо
        ///                                    привязывания новой последовательности запросов к группе последовательностей
        ///                                    запросов.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Необходим для привязывания запроса к последовательности запросов либо привязывани" +
            "я новой последовательности запросов к группе последовательностей запросов.")]
        [System.Xml.Serialization.XmlElementAttribute("linkedGroupIdentity")]
        public LinkedGroupIdentity LinkedGroupIdentity { get; set; }

        /// <summary>
        /// <para>Необходим для формирования Адаптером СМЭВ кода транзакции в случаях,
        ///                                    если //linkedGroupIdentity не передаются вместе с запросом.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Необходим для формирования Адаптером СМЭВ кода транзакции в случаях, если //linke" +
            "dGroupIdentity не передаются вместе с запросом.")]
        [System.Xml.Serialization.XmlElementAttribute("createGroupIdentity")]
        public CreateGroupIdentity CreateGroupIdentity { get; set; }

        /// <summary>
        /// <para>Идентификатор нода (узла) отправителя запроса.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор нода (узла) отправителя запроса.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("nodeId")]
        public string NodeId { get; set; }

        /// <summary>
        /// <para>Ограничение времени жизни запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ограничение времени жизни запроса.")]
        [System.Xml.Serialization.XmlElementAttribute("eol", DataType = "dateTime")]
        public System.DateTime Eol { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Eol property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EolSpecified { get; set; }

        /// <summary>
        /// <para>Флаг, указывающий на тестовое сообщение.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Флаг, указывающий на тестовое сообщение.")]
        [System.Xml.Serialization.XmlElementAttribute("testMessage")]
        public bool TestMessage { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TestMessage property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestMessageSpecified { get; set; }

        /// <summary>
        /// <para>Код транзакции, заполняемый ИС УВ из исходного запроса (возможно даже другого ВС) .</para>
        /// <para xml:lang="en">Maximum length: 1500.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код транзакции, заполняемый ИС УВ из исходного запроса (возможно даже другого ВС)" +
            " .")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1500)]
        [System.Xml.Serialization.XmlElementAttribute("TransactionCode")]
        public string TransactionCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BusinessProcessMetadata")]
        public BusinessProcessMetadata BusinessProcessMetadata { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RoutingInformation")]
        public RoutingInformationType RoutingInformation { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Metadata", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestMetadataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseMetadataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusMetadataType))]
    public partial class Metadata
    {

        /// <summary>
        /// <para>Клиентский идентификатор сообщения (запроса либо ответа на запрос) в виде уникальной
        ///                        произвольной последовательности цифр и/или латинских букв.
        ///                        Данный элемент заполняется ИС УВ при отправке сообщения (запроса либо ответа на запрос) в
        ///                        адаптер.
        ///                        При получении ИС УВ сообщения (запроса либо ответа на запрос) из адаптера данный элемент
        ///                        заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Клиентский идентификатор сообщения (запроса либо ответа на запрос) в виде уникальной произвольной последовательности цифр и/или латинских букв. Данный элемент заполняется ИС УВ при отправке сообщения (запроса либо ответа на запрос) в адаптер. При получении ИС УВ сообщения (запроса либо ответа на запрос) из адаптера данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string ClientId { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LinkedGroupIdentity", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkedGroupIdentity
    {

        /// <summary>
        /// <para>Клиентский идентификатор запроса источника.
        ///                        Указывается clientId родительского запроса по отношению к текущему запросу последовательности
        ///                        запросов.
        ///                        Данный элемент заполняется ИС УВ при отправке запроса в адаптер.
        ///                        При получении ИС УВ запроса из адаптера данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Клиентский идентификатор запроса источника. Указывается clientId родительского запроса по отношению к текущему запросу последовательности запросов. Данный элемент заполняется ИС УВ при отправке запроса в адаптер. При получении ИС УВ запроса из адаптера данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("refClientId")]
        public string RefClientId { get; set; }

        /// <summary>
        /// <para>Клиентская ссылка на группу последовательностей запросов, представляющая собой
        ///                        клиентский идентификатор корневого запроса существующей последовательности запросов,
        ///                        с которой необходимо объединить в общую группу новую последовательность запросов.
        ///                        Указывается id корневого запроса существующей последовательности запросов,
        ///                        с которой следует объединить в общую группу последовательность запросов,
        ///                        корневым элементом которой является текущий запрос.
        ///                        Данный элемент заполняется ИС УВ при отправке запроса в адаптер.
        ///                        При получении ИС УВ запроса из адаптера данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Клиентская ссылка на группу последовательностей запросов, представляющая собой клиентский идентификатор корневого запроса существующей последовательности запросов, с которой необходимо объединить в общую группу новую последовательность запросов. Указывается id корневого запроса существующей последовательности запросов, с которой следует объединить в общую группу последовательность запросов, корневым элементом которой является текущий запрос. Данный элемент заполняется ИС УВ при отправке запроса в адаптер. При получении ИС УВ запроса из адаптера данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("refGroupId")]
        public string RefGroupId { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CreateGroupIdentity", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateGroupIdentity
    {

        /// <summary>
        /// <para>Код ФРГУ государственной услуги либо государственной функции.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код ФРГУ государственной услуги либо государственной функции.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FRGUServiceCode")]
        public string FrguServiceCode { get; set; }

        /// <summary>
        /// <para>Расширенные сведения об услуге или функции.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Расширенные сведения об услуге или функции.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlElementAttribute("FRGUServiceDescription")]
        public string FrguServiceDescription { get; set; }

        /// <summary>
        /// <para>Расширенные сведения о потребителе услуги или функции.</para>
        /// <para xml:lang="en">Maximum length: 1000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Расширенные сведения о потребителе услуги или функции.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1000)]
        [System.Xml.Serialization.XmlElementAttribute("FRGUServiceRecipientDescription")]
        public string FrguServiceRecipientDescription { get; set; }
    }

    /// <summary>
    /// <para>Информация о бизнес-процессе, в рамках которого пересылается сообщение.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Информация о бизнес-процессе, в рамках которого пересылается сообщение.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BusinessProcessMetadata", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BusinessProcessMetadata", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class BusinessProcessMetadata
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlElement> _any;

        /// <summary>
        /// <para>Корневой элемент XML-документа присоединять сюда.
        ///                        Формат данных XML-документа определяется отдельной схемой (схемах).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Корневой элемент XML-документа присоединять сюда. Формат данных XML-документа опр" +
            "еделяется отдельной схемой (схемах).")]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BusinessProcessMetadata" /> class.</para>
        /// </summary>
        public BusinessProcessMetadata()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.XmlElement>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RoutingInformationType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoutingInformationType
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _dynamicRouting;

        [System.Xml.Serialization.XmlArrayAttribute("DynamicRouting")]
        [System.Xml.Serialization.XmlArrayItemAttribute("DynamicValue", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<string> DynamicRouting
        {
            get
            {
                return _dynamicRouting;
            }
            private set
            {
                _dynamicRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DynamicRouting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DynamicRoutingSpecified
        {
            get
            {
                return (this.DynamicRouting.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RoutingInformationType" /> class.</para>
        /// </summary>
        public RoutingInformationType()
        {
            this._dynamicRouting = new System.Collections.ObjectModel.Collection<string>();
            this._identifierRouting = new System.Collections.ObjectModel.Collection<string>();
            this._registryRouting = new System.Collections.ObjectModel.Collection<RegistryRecordRoutingType>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _identifierRouting;

        [System.Xml.Serialization.XmlArrayAttribute("IdentifierRouting")]
        [System.Xml.Serialization.XmlArrayItemAttribute("IdentifierValue", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<string> IdentifierRouting
        {
            get
            {
                return _identifierRouting;
            }
            private set
            {
                _identifierRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IdentifierRouting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentifierRoutingSpecified
        {
            get
            {
                return (this.IdentifierRouting.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RegistryRecordRoutingType> _registryRouting;

        [System.Xml.Serialization.XmlArrayAttribute("RegistryRouting")]
        [System.Xml.Serialization.XmlArrayItemAttribute("RegistryRecordRouting", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<RegistryRecordRoutingType> RegistryRouting
        {
            get
            {
                return _registryRouting;
            }
            private set
            {
                _registryRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RegistryRouting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistryRoutingSpecified
        {
            get
            {
                return (this.RegistryRouting.Count != 0);
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DynamicRoutingType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DynamicRoutingType
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _dynamicValue;

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DynamicValue")]
        public System.Collections.ObjectModel.Collection<string> DynamicValue
        {
            get
            {
                return _dynamicValue;
            }
            private set
            {
                _dynamicValue = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DynamicRoutingType" /> class.</para>
        /// </summary>
        public DynamicRoutingType()
        {
            this._dynamicValue = new System.Collections.ObjectModel.Collection<string>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentifierRoutingType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentifierRoutingType
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _identifierValue;

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("IdentifierValue")]
        public System.Collections.ObjectModel.Collection<string> IdentifierValue
        {
            get
            {
                return _identifierValue;
            }
            private set
            {
                _identifierValue = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="IdentifierRoutingType" /> class.</para>
        /// </summary>
        public IdentifierRoutingType()
        {
            this._identifierValue = new System.Collections.ObjectModel.Collection<string>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryRoutingType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistryRoutingType
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RegistryRecordRoutingType> _registryRecordRouting;

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RegistryRecordRouting")]
        public System.Collections.ObjectModel.Collection<RegistryRecordRoutingType> RegistryRecordRouting
        {
            get
            {
                return _registryRecordRouting;
            }
            private set
            {
                _registryRecordRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RegistryRoutingType" /> class.</para>
        /// </summary>
        public RegistryRoutingType()
        {
            this._registryRecordRouting = new System.Collections.ObjectModel.Collection<RegistryRecordRoutingType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryRecordRoutingType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistryRecordRoutingType
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RecordId")]
        public int RecordId { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("UseGeneralRouting")]
        public bool UseGeneralRouting { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _dynamicRouting;

        [System.Xml.Serialization.XmlArrayAttribute("DynamicRouting")]
        [System.Xml.Serialization.XmlArrayItemAttribute("DynamicValue", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<string> DynamicRouting
        {
            get
            {
                return _dynamicRouting;
            }
            private set
            {
                _dynamicRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DynamicRouting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DynamicRoutingSpecified
        {
            get
            {
                return (this.DynamicRouting.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RegistryRecordRoutingType" /> class.</para>
        /// </summary>
        public RegistryRecordRoutingType()
        {
            this._dynamicRouting = new System.Collections.ObjectModel.Collection<string>();
            this._identifierRouting = new System.Collections.ObjectModel.Collection<string>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _identifierRouting;

        [System.Xml.Serialization.XmlArrayAttribute("IdentifierRouting")]
        [System.Xml.Serialization.XmlArrayItemAttribute("IdentifierValue", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<string> IdentifierRouting
        {
            get
            {
                return _identifierRouting;
            }
            private set
            {
                _identifierRouting = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IdentifierRouting collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentifierRoutingSpecified
        {
            get
            {
                return (this.IdentifierRouting.Count != 0);
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseMetadataType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseMetadata", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class ResponseMetadataType : Metadata
    {

        /// <summary>
        /// <para>Клиентский идентификатор запроса, на который высылается ответ.
        ///                                Данный элемент заполняется ИС УВ при отправке ответа на запрос в адаптер.
        ///                                При получении ИС УВ ответа на запрос из адаптера данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(
            "Клиентский идентификатор запроса, на который высылается ответ. " +
            "Данный элемент заполняется ИС УВ при отправке ответа на запрос в адаптер. " +
            "При получении ИС УВ ответа на запрос из адаптера данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("replyToClientId")]
        public string ReplyToClientId { get; set; }

        /// <summary>
        /// <para>Строка replyTo из оригинального запроса</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Строка replyTo из оригинального запроса")]
        [System.Xml.Serialization.XmlElementAttribute("replyTo")]
        public string ReplyTo { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequestContentType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RequestContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class RequestContentType
    {

        /// <summary>
        /// <para>Бизнес данные запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Бизнес данные запроса.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("content")]
        public Content Content { get; set; }

        /// <summary>
        /// <para>Оригинальный запрос.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Оригинальный запрос.")]
        [System.Xml.Serialization.XmlElementAttribute("originalContent")]
        public string OriginalContent { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Content", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Content
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("MessagePrimaryContent")]
        public MessagePrimaryContent MessagePrimaryContent { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PersonalSignature")]
        public XmldSigSignatureType PersonalSignature { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttachmentHeaderType> _attachmentHeaderList;

        [System.Xml.Serialization.XmlArrayAttribute("AttachmentHeaderList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("AttachmentHeader", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<AttachmentHeaderType> AttachmentHeaderList
        {
            get
            {
                return _attachmentHeaderList;
            }
            private set
            {
                _attachmentHeaderList = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AttachmentHeaderList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttachmentHeaderListSpecified
        {
            get
            {
                return (this.AttachmentHeaderList.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Content" /> class.</para>
        /// </summary>
        public Content()
        {
            this._attachmentHeaderList = new System.Collections.ObjectModel.Collection<AttachmentHeaderType>();
        }
    }

    /// <summary>
    /// <para>Содержательная часть сообщения СМЭВ.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Содержательная часть сообщения СМЭВ.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MessagePrimaryContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MessagePrimaryContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class MessagePrimaryContent
    {

        /// <summary>
        /// <para>Корневой элемент XML-документа запроса присоединять сюда.
        ///                            Формат данных XML-документа определяется схемой вида сведений, зарегистрированного в СМЭВ 3</para>
        /// </summary>
        public string Any { get; set; }
    }

    /// <summary>
    /// <para>ЭП-СП содержательной части сообщения.
    ///                Подписывается элемент, находящийся сразу под //MessagePrimaryContent.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("ЭП-СП содержательной части сообщения. Подписывается элемент, находящийся сразу под //MessagePrimaryContent.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("XMLDSigSignatureType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PersonalSignature", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class XmldSigSignatureType
    {

        /// <summary>
        /// <para>Электронная подпись, по спецификации XMLDSig.
        ///                        Объявлена как any для того, чтобы инструменты типа JAXB не генерировали классов для пространства
        ///                        имён http://www.w3.org/2000/09/xmldsig#.
        ///                        Это, в свою очередь, нужно потому, что инструменты, генерирующие и проверяющие ЭЦП (напр. Apache
        ///                        Santuario)
        ///                        работают с DOM-деревьями, а не с JAXB-объектами.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Электронная подпись, по спецификации XMLDSig. Объявлена как any для того, чтобы инструменты типа JAXB не генерировали классов для пространства имён http://www.w3.org/2000/09/xmldsig#. Это, в свою очередь, нужно потому, что инструменты, генерирующие и проверяющие ЭЦП (напр. Apache Santuario) работают с DOM-деревьями, а не с JAXB-объектами.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any { get; set; }
    }

    /// <summary>
    /// <para>Пути к файлам вложения, прилагаемого к сообщению.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Пути к файлам вложения, прилагаемого к сообщению.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AttachmentHeaderList", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AttachmentHeaderList", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class AttachmentHeaderList
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttachmentHeaderType> _attachmentHeader;

        /// <summary>
        /// <para>Путь к файлу вложения, прилагаемого к сообщению.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Путь к файлу вложения, прилагаемого к сообщению.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("AttachmentHeader")]
        public System.Collections.ObjectModel.Collection<AttachmentHeaderType> AttachmentHeader
        {
            get
            {
                return _attachmentHeader;
            }
            private set
            {
                _attachmentHeader = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttachmentHeaderList" /> class.</para>
        /// </summary>
        public AttachmentHeaderList()
        {
            this._attachmentHeader = new System.Collections.ObjectModel.Collection<AttachmentHeaderType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AttachmentHeaderType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AttachmentHeaderType
    {

        /// <summary>
        /// <para>Идентификатор вложения в строковом представлении UUID.
        ///                        Данный идентификатор используется в СМЭВ 3 для процессинга вложений.
        ///                        Идентификатор указывается только в том случае, если надо вручную указать
        ///                        идентификатор вложения при отправке в файловое хранилище.
        ///                        Для отправки вложения в файловое хранилище, необходимо указать режим передачи вложения
        ///                        REFERENCE.</para>
        /// <para xml:lang="en">Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Идентификатор вложения в строковом представлении UUID. Данный идентификатор используется в СМЭВ 3 для процессинга вложений. Идентификатор указывается только в том случае, если надо вручную указать идентификатор вложения при отправке в файловое хранилище. Для отправки вложения в файловое хранилище, необходимо указать режим передачи вложения REFERENCE.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")]
        [System.Xml.Serialization.XmlElementAttribute("Id")]
        public string Id { get; set; }

        /// <summary>
        /// <para>Полный (абсолютный) либо относительный путь к файлу вложения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Полный (абсолютный) либо относительный путь к файлу вложения.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("filePath")]
        public string FilePath { get; set; }

        /// <summary>
        /// <para>Идентификатор паспорта вложения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор паспорта вложения.")]
        [System.Xml.Serialization.XmlElementAttribute("passportId")]
        public string PassportId { get; set; }

        /// <summary>
        /// <para>ЭЦП в формате PKCS#7 detached. Подписывать ключом ЭП-СП.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ЭЦП в формате PKCS#7 detached. Подписывать ключом ЭП-СП.")]
        [System.Xml.Serialization.XmlElementAttribute("SignaturePKCS7", DataType = "base64Binary")]
        public byte[] SignaturePkcs7 { get; set; }

        /// <summary>
        /// <para>Режим передачи вложения.
        ///                        Режим указывается только в том случае, если надо вручную указать
        ///                        режим передачи вложения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Режим передачи вложения. Режим указывается только в том случае, если надо вручную" +
            " указать режим передачи вложения.")]
        [System.Xml.Serialization.XmlElementAttribute("TransferMethod")]
        public TransferMethodType TransferMethod { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TransferMethod property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransferMethodSpecified { get; set; }

        /// <summary>
        /// <para>Переиспользуемое вложение.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Переиспользуемое вложение.")]
        [System.Xml.Serialization.XmlElementAttribute("ReusableAttachment")]
        public bool ReusableAttachment { get; set; }

        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReusableAttachment property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReusableAttachmentSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FileType> _archive;

        /// <summary>
        /// <para>Объявление передаваемых файлов в архиве.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Объявление передаваемых файлов в архиве.")]
        [System.Xml.Serialization.XmlArrayAttribute("Archive")]
        [System.Xml.Serialization.XmlArrayItemAttribute("File", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
        public System.Collections.ObjectModel.Collection<FileType> Archive
        {
            get
            {
                return _archive;
            }
            private set
            {
                _archive = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Archive collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchiveSpecified
        {
            get
            {
                return (this.Archive.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttachmentHeaderType" /> class.</para>
        /// </summary>
        public AttachmentHeaderType()
        {
            this._archive = new System.Collections.ObjectModel.Collection<FileType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransferMethodType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum TransferMethodType
    {

        /// <summary>
        /// <para>В составе сообщения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("В составе сообщения.")]
        [System.Xml.Serialization.XmlEnumAttribute("MTOM")]
        Mtom,

        /// <summary>
        /// <para>Отдельно от сообщения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Отдельно от сообщения.")]
        [System.Xml.Serialization.XmlEnumAttribute("REFERENCE")]
        Reference,
    }

    /// <summary>
    /// <para>Объявление передаваемых файлов в архиве.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Объявление передаваемых файлов в архиве.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ArchiveType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArchiveType
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FileType> _file;

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public System.Collections.ObjectModel.Collection<FileType> File
        {
            get
            {
                return _file;
            }
            private set
            {
                _file = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ArchiveType" /> class.</para>
        /// </summary>
        public ArchiveType()
        {
            this._file = new System.Collections.ObjectModel.Collection<FileType>();
        }
    }

    /// <summary>
    /// <para>Описание файла</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Описание файла")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FileType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileType
    {

        /// <summary>
        /// <para>Наименование файла.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Наименование файла.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }

        /// <summary>
        /// <para>Идентификатор паспорта вложения.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор паспорта вложения.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("passportId")]
        public string PassportId { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseContentType", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseContent", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class ResponseContentType
    {

        /// <summary>
        /// <para>Бизнес данные ответа на запрос.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Бизнес данные ответа на запрос.")]
        [System.Xml.Serialization.XmlElementAttribute("content")]
        public Content Content { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Reject> _rejects;

        /// <summary>
        /// <para>Отклонение запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Отклонение запроса.")]
        [System.Xml.Serialization.XmlElementAttribute("rejects")]
        public System.Collections.ObjectModel.Collection<Reject> Rejects
        {
            get
            {
                return _rejects;
            }
            private set
            {
                _rejects = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Rejects collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RejectsSpecified
        {
            get
            {
                return (this.Rejects.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ResponseContentType" /> class.</para>
        /// </summary>
        public ResponseContentType()
        {
            this._rejects = new System.Collections.ObjectModel.Collection<Reject>();
        }

        /// <summary>
        /// <para>Бизнес статус запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Бизнес статус запроса.")]
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public Status Status { get; set; }

        /// <summary>
        /// <para>Оригинальный ответ.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Оригинальный ответ.")]
        [System.Xml.Serialization.XmlElementAttribute("originalContent")]
        public string OriginalContent { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Reject", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Reject
    {

        /// <summary>
        /// <para>Код причины отклонения запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код причины отклонения запроса.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public RejectCode Code { get; set; }

        /// <summary>
        /// <para>Описание причины отклонения запроса.</para>
        /// <para xml:lang="en">Maximum length: 4000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание причины отклонения запроса.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Status", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Status
    {

        /// <summary>
        /// <para>Код бизнес статуса запроса.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Код бизнес статуса запроса.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public string Code { get; set; }

        /// <summary>
        /// <para>Описание бизнес статуса запроса.</para>
        /// <para xml:lang="en">Maximum length: 4000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание бизнес статуса запроса.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<StatusParameter> _parameter;

        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public System.Collections.ObjectModel.Collection<StatusParameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Status" /> class.</para>
        /// </summary>
        public Status()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<StatusParameter>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatusParameter", Namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusParameter
    {

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("key")]
        public string Key { get; set; }

        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string Value { get; set; }
    }

    /// <summary>
    /// Тело сообщения адаптера
    /// </summary>
    public partial class Message : IMessage
    {
        /// <summary>
        /// Тип сообщения
        /// </summary>
        [Newtonsoft.Json.JsonProperty("messageType")]
        public SMEV.Adapter.Types.Enums.MessageType MessageType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequestMessageType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("RequestMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class RequestMessageType : Message
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RequestMetadata")]
        public RequestMetadataType RequestMetadata { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RequestContent")]
        public RequestContentType RequestContent { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseMessageType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class ResponseMessageType : Message
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("responseMetadata")]
        public ResponseMetadataType ResponseMetadata { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("responseContent")]
        public ResponseContentType ResponseContent { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QueryMessageType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("QueryMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class QueryMessageType : Message
    {
        /// <summary>
        /// <para>Клиентский идентификатор сообщения (запроса либо ответа на запрос) в виде уникальной
        ///                                произвольной последовательности цифр и/или латинских букв.
        ///                                Данный элемент заполняется ИС УВ при отправке сообщения (запроса либо ответа на запрос) в
        ///                                адаптер.
        ///                                При получении ИС УВ сообщения (запроса либо ответа на запрос) из адаптера данный элемент
        ///                                заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Клиентский идентификатор сообщения (запроса либо ответа на запрос) в виде уникальной произвольной последовательности цифр и/или латинских букв. Данный элемент заполняется ИС УВ при отправке сообщения (запроса либо ответа на запрос) в адаптер. При получении ИС УВ сообщения (запроса либо ответа на запрос) из адаптера данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string ClientId { get; set; }
        
        /// <summary>
        /// <para>Идентификатор нода (узла) отправителя запроса.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор нода (узла) отправителя запроса.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("nodeId")]
        public string NodeId { get; set; }
        
        /// <summary>
        /// <para>Тип запроса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Тип запроса.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("queryType")]
        public QueryMessageTypeQueryType QueryType { get; set; }
        
        /// <summary>
        /// <para>Фильтр.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Фильтр.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("queryFilter")]
        public string QueryFilter { get; set; }
        
        /// <summary>
        /// <para>Корневой тег фильтра.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Корневой тег фильтра.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("queryRootTag")]
        public string QueryRootTag { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QueryMessageTypeQueryType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType=true)]
    public enum QueryMessageTypeQueryType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("REQUEST")]
        Request,
        
        [System.Xml.Serialization.XmlEnumAttribute("RESPONSE")]
        Response,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SyncRequest", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SyncRequest", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class SyncRequest
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itSystem")]
        public string ItSystem { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RequestMessage")]
        public RequestMessageType RequestMessage { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SyncResponse", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SyncResponse", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class SyncResponse
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("smevMetadata")]
        public SmevMetadata SmevMetadata { get; set; }
        
        /// <summary>
        /// <para>Для //SyncResponse возвращается блок
        ///                        //ResponseMessage или //ErrorMessage</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Для //SyncResponse возвращается блок //ResponseMessage или //ErrorMessage")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("message")]
        public Message Message { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SmevMetadata", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("smevMetadata", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class SmevMetadata
    {
        
        /// <summary>
        /// <para>Идентификатор сообщения (запроса либо ответа на запрос) в строковом представлении UUID.
        ///                        Данный идентификатор используется в СМЭВ 3 для процессинга сообщений.
        ///                        Генерируется адаптером при отправке сообщения в СМЭВ 3
        ///                        в соответствии с RFC-4122, по варианту 1 (на основании MAC-адреса и текущего
        ///                        времени).
        ///                        Также идентификатор сообщения приходит в адаптер из СМЭВ 3 вместе с запросом либо ответом на
        ///                        запрос.
        ///                        Данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Идентификатор сообщения (запроса либо ответа на запрос) в строковом представлении UUID. Данный идентификатор используется в СМЭВ 3 для процессинга сообщений. Генерируется адаптером при отправке сообщения в СМЭВ 3 в соответствии с RFC-4122, по варианту 1 (на основании MAC-адреса и текущего времени). Также идентификатор сообщения приходит в адаптер из СМЭВ 3 вместе с запросом либо ответом на запрос. Данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")]
        [System.Xml.Serialization.XmlElementAttribute("messageId")]
        public string MessageId { get; set; }
        
        /// <summary>
        /// <para>Идентификатор корневого запроса (запроса, порождающего цепочку запросов) в строковом
        ///                        представлении UUID.
        ///                        Соответствует RFC-4122, по варианту 1 (на основании MAC-адреса и текущего
        ///                        времени).
        ///                        Также данный идентификатор приходит в адаптер из СМЭВ 3 вместе с запросом.
        ///                        Данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Идентификатор корневого запроса (запроса, порождающего цепочку запросов) в строковом представлении UUID. Соответствует RFC-4122, по варианту 1 (на основании MAC-адреса и текущего времени). Также данный идентификатор приходит в адаптер из СМЭВ 3 вместе с запросом. Данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")]
        [System.Xml.Serialization.XmlElementAttribute("referenceMessageID")]
        public string ReferenceMessageId { get; set; }
        
        /// <summary>
        /// <para>Код транзакции.
        ///                        При отправке запроса в СМЭВ 3 адаптер формирует код транзакции самостоятельно.
        ///                        Также код транзакции приходит в адаптер из СМЭВ 3 вместе с запросом либо ответом на запрос.
        ///                        Адаптер заполняет данный элемент кодом транзакции, полученным из СМЭВ 3.</para>
        /// <para xml:lang="en">Maximum length: 1500.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Код транзакции. При отправке запроса в СМЭВ 3 адаптер формирует код транзакции самостоятельно. Также код транзакции приходит в адаптер из СМЭВ 3 вместе с запросом либо ответом на запрос. Адаптер заполняет данный элемент кодом транзакции, полученным из СМЭВ 3.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1500)]
        [System.Xml.Serialization.XmlElementAttribute("transactionCode")]
        public string TransactionCode { get; set; }
        
        /// <summary>
        /// <para>Идентификатор запроса, на который пришел ответ, в строковом представлении UUID.
        ///                        Данный идентификатор используется в СМЭВ 3 для процессинга ответов на запросы.
        ///                        Соответствует RFC-4122, по варианту 1 (на основании MAC-адреса и текущего
        ///                        времени).
        ///                        Приходит в адаптер из СМЭВ 3 вместе с ответом на запрос.
        ///                        Данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Идентификатор запроса, на который пришел ответ, в строковом представлении UUID. Данный идентификатор используется в СМЭВ 3 для процессинга ответов на запросы. Соответствует RFC-4122, по варианту 1 (на основании MAC-адреса и текущего времени). Приходит в адаптер из СМЭВ 3 вместе с ответом на запрос. Данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")]
        [System.Xml.Serialization.XmlElementAttribute("originalMessageID")]
        public string OriginalMessageId { get; set; }
        
        /// <summary>
        /// <para>Мнемоника системы отправителя.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Мнемоника системы отправителя.")]
        [System.Xml.Serialization.XmlElementAttribute("sender")]
        public string Sender { get; set; }
        
        /// <summary>
        /// <para>Мнемоника системы получателя.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Мнемоника системы получателя.")]
        [System.Xml.Serialization.XmlElementAttribute("recipient")]
        public string Recipient { get; set; }
        
        /// <summary>
        /// <para>Строка replyTo из оригинального запроса</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Строка replyTo из оригинального запроса")]
        [System.Xml.Serialization.XmlElementAttribute("replyTo")]
        public string ReplyTo { get; set; }
        
        /// <summary>
        /// <para>Дата и время создания запроса или ответа на запрос</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Дата и время создания запроса или ответа на запрос")]
        [System.Xml.Serialization.XmlElementAttribute("sendingDate", DataType="dateTime")]
        public System.DateTime SendingDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SendingDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendingDateSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClientMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ClientMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class ClientMessage
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itSystem")]
        public string ItSystem { get; set; }
        
        /// <summary>
        /// <para>Имя очереди куда надо отправить ответ и все статусы</para>
        /// <para xml:lang="en">Maximum length: 1500.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Имя очереди куда надо отправить ответ и все статусы")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1500)]
        [System.Xml.Serialization.XmlElementAttribute("replyToQueue")]
        public string ReplyToQueue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("RequestMessage")]
        public RequestMessageType RequestMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ResponseMessage")]
        public ResponseMessageType ResponseMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("QueryMessage")]
        public QueryMessageType QueryMessage { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdapterMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("QueryResult", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class AdapterMessage
    {
        [Newtonsoft.Json.JsonProperty("smevMetadata")]
        public SmevMetadata SmevMetadata { get; set; }

        [Newtonsoft.Json.JsonProperty("message")]
        public IMessage Message { get; set; }
    }

    /// <summary>
    /// Интерфейс для де/сериализации данных сообщения адаптера
    /// </summary>
    public interface IMessage
    {
        /// <summary>
        /// Тип сообщения
        /// </summary>
        [Newtonsoft.Json.JsonProperty("messageType")]
        public SMEV.Adapter.Types.Enums.MessageType MessageType { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatusMessageCategory", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum StatusMessageCategory
    {
        
        /// <summary>
        /// <para>Иной статус.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Иной статус.")]
        [System.Xml.Serialization.XmlEnumAttribute("OTHER")]
        Other,
        
        /// <summary>
        /// <para>Ошибка.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ошибка.")]
        [System.Xml.Serialization.XmlEnumAttribute("ERROR")]
        Error,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatusMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("StatusMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorMessage))]
    public partial class StatusMessage : Message
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("statusMetadata")]
        public StatusMetadataType StatusMetadata { get; set; }
        
        /// <summary>
        /// <para>Тип статусного сообщения.
        ///                                Сообщения типа "ERROR" возвращаются блоком //ErrorMessage
        ///                                Сообщения типа "OTHER" возвращаются блоком //StatusMessage</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Тип статусного сообщения. Сообщения типа \"ERROR\" возвращаются блоком //ErrorMessa" +
            "ge Сообщения типа \"OTHER\" возвращаются блоком //StatusMessage")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public StatusMessageCategory Status { get; set; }
        
        /// <summary>
        /// <para>Описание статуса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Описание статуса.")]
        [System.Xml.Serialization.XmlElementAttribute("details")]
        public string Details { get; set; }
        
        /// <summary>
        /// <para>Метка времени формирования статуса.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Метка времени формирования статуса.")]
        [System.Xml.Serialization.XmlElementAttribute("timestamp", DataType="dateTime")]
        public System.DateTime Timestamp { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Timestamp property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatusMetadataType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusMetadataType : Metadata
    {
        
        /// <summary>
        /// <para>Клиентский идентификатор сообщения, на который высылается статусный ответ.
        ///                                При получении ИС УВ статусного ответа данный элемент заполняется адаптером.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Клиентский идентификатор сообщения, на который высылается статусный ответ. При по" +
            "лучении ИС УВ статусного ответа данный элемент заполняется адаптером.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("originalClientId")]
        public string OriginalClientId { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ErrorType", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public enum ErrorType
    {
        
        /// <summary>
        /// <para>Ошибка сервера (СМЭВ 3).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ошибка сервера (СМЭВ 3).")]
        [System.Xml.Serialization.XmlEnumAttribute("SERVER")]
        Server,
        
        /// <summary>
        /// <para>Ошибка клиента (Адаптера СМЭВ 3).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ошибка клиента (Адаптера СМЭВ 3).")]
        [System.Xml.Serialization.XmlEnumAttribute("CLIENT")]
        Client,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ErrorMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ErrorMessage", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class ErrorMessage : StatusMessage
    {
        
        /// <summary>
        /// <para>Тип источника ошибки.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Тип источника ошибки.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public ErrorType Type { get; set; }
        
        /// <summary>
        /// <para>Сведения об ошибке.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Сведения об ошибке.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fault")]
        public SMEV.Adapter.XsdTypes.Fault Fault { get; set; }
    }
    
    /// <summary>
    /// <para>Получить сообщение из очереди информационной системы участника взаимодействия, если очередь не пуста.
    ///                В какую очередь смотреть - определаятся регистрационным кодом информационной системы участника
    ///                взаимодействия в Адаптере СМЭВ.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Получить сообщение из очереди информационной системы участника взаимодействия, если очередь не пуста. В какую очередь смотреть - определаятся регистрационным кодом информационной системы участника взаимодействия в Адаптере СМЭВ.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MessageQuery", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MessageQuery", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class MessageQuery
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itSystem")]
        public string ItSystem { get; set; }
        
        /// <summary>
        /// <para>Идентификатор нода (узла).</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор нода (узла).")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("nodeId")]
        public string NodeId { get; set; }
        
        /// <summary>
        /// <para>Идентификатор выделенной очереди.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор выделенной очереди.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("routerExtraQueue")]
        public string RouterExtraQueue { get; set; }
        
        /// <summary>
        /// <para>Запрос одного сообщения по его типу (описание см. в //QueryTypeCriteria).
        ///                        Если запрос осуществляется без идентификатора, то будет возвращено одно очередное сообщение из
        ///                        очереди информационной системы участника взаимодействия.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Запрос одного сообщения по его типу (описание см. в //QueryTypeCriteria). Если за" +
            "прос осуществляется без идентификатора, то будет возвращено одно очередное сообщ" +
            "ение из очереди информационной системы участника взаимодействия.")]
        [System.Xml.Serialization.XmlElementAttribute("specificQuery")]
        public QueryTypeCriteria SpecificQuery { get; set; }
    }
    
    /// <summary>
    /// <para>Найти сообщения отправленные либо полученные информационной системой участника взаимодействия.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Найти сообщения отправленные либо полученные информационной системой участника вз" +
        "аимодействия.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FindMessageQuery", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("FindMessageQuery", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class FindMessageQuery
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itSystem")]
        public string ItSystem { get; set; }
        
        /// <summary>
        /// <para>Поиск сообщений по идентификатору либо по заданному периоду времени.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Поиск сообщений по идентификатору либо по заданному периоду времени.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("specificQuery")]
        public FindTypeCriteria SpecificQuery { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QueryResultList", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("QueryResultList", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class QueryResultList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdapterMessage> _queryResult;
        
        [System.Xml.Serialization.XmlElementAttribute("queryResult")]
        public System.Collections.ObjectModel.Collection<AdapterMessage> QueryResult
        {
            get
            {
                return _queryResult;
            }
            set
            {
                _queryResult = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the QueryResult collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QueryResultSpecified
        {
            get
            {
                return (this.QueryResult.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="QueryResultList" /> class.</para>
        /// </summary>
        public QueryResultList()
        {
            this._queryResult = new System.Collections.ObjectModel.Collection<AdapterMessage>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MessageResult", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MessageResult", Namespace="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")]
    public partial class MessageResult
    {
        
        /// <summary>
        /// <para>Мнемоника ИС</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itSystem")]
        public string ItSystem { get; set; }
        
        /// <summary>
        /// <para>Идентификатор отправленного сообщения в строковом представлении UUID.</para>
        /// <para xml:lang="en">Pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Идентификатор отправленного сообщения в строковом представлении UUID.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("MessageId")]
        public string MessageId { get; set; }
    }
}
